/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/eZmaxAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/eZmaxAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EZmaxApiDefinitionFull);
  }
}(this, function(expect, EZmaxApiDefinitionFull) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EZmaxApiDefinitionFull.ObjectDiscussionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ObjectDiscussionApi', function() {
    describe('discussionCreateObjectV1', function() {
      it('should call discussionCreateObjectV1 successfully', function(done) {
        //uncomment below and update the code to test discussionCreateObjectV1
        //instance.discussionCreateObjectV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('discussionDeleteObjectV1', function() {
      it('should call discussionDeleteObjectV1 successfully', function(done) {
        //uncomment below and update the code to test discussionDeleteObjectV1
        //instance.discussionDeleteObjectV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('discussionGetObjectV2', function() {
      it('should call discussionGetObjectV2 successfully', function(done) {
        //uncomment below and update the code to test discussionGetObjectV2
        //instance.discussionGetObjectV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('discussionPatchObjectV1', function() {
      it('should call discussionPatchObjectV1 successfully', function(done) {
        //uncomment below and update the code to test discussionPatchObjectV1
        //instance.discussionPatchObjectV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('discussionUpdateDiscussionreadstatusV1', function() {
      it('should call discussionUpdateDiscussionreadstatusV1 successfully', function(done) {
        //uncomment below and update the code to test discussionUpdateDiscussionreadstatusV1
        //instance.discussionUpdateDiscussionreadstatusV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
