/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommonResponseError from '../model/CommonResponseError';
import SystemconfigurationEditObjectV1Request from '../model/SystemconfigurationEditObjectV1Request';
import SystemconfigurationEditObjectV1Response from '../model/SystemconfigurationEditObjectV1Response';
import SystemconfigurationGetObjectV2Response from '../model/SystemconfigurationGetObjectV2Response';

/**
* ObjectSystemconfiguration service.
* @module eZmaxAPI/api/ObjectSystemconfigurationApi
* @version 1.2.0
*/
export default class ObjectSystemconfigurationApi {

    /**
    * Constructs a new ObjectSystemconfigurationApi. 
    * @alias module:eZmaxAPI/api/ObjectSystemconfigurationApi
    * @class
    * @param {module:eZmaxAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:eZmaxAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the systemconfigurationEditObjectV1 operation.
     * @callback module:eZmaxAPI/api/ObjectSystemconfigurationApi~systemconfigurationEditObjectV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/SystemconfigurationEditObjectV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit an existing Systemconfiguration
     * 
     * @param {Number} pkiSystemconfigurationID The unique ID of the Systemconfiguration
     * @param {module:eZmaxAPI/model/SystemconfigurationEditObjectV1Request} SystemconfigurationEditObjectV1Request 
     * @param {module:eZmaxAPI/api/ObjectSystemconfigurationApi~systemconfigurationEditObjectV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/SystemconfigurationEditObjectV1Response}
     */
    systemconfigurationEditObjectV1(pkiSystemconfigurationID, SystemconfigurationEditObjectV1Request, callback) {
      let postBody = SystemconfigurationEditObjectV1Request;
      // verify the required parameter 'pkiSystemconfigurationID' is set
      if (pkiSystemconfigurationID === undefined || pkiSystemconfigurationID === null) {
        throw new Error("Missing the required parameter 'pkiSystemconfigurationID' when calling systemconfigurationEditObjectV1");
      }
      // verify the required parameter 'SystemconfigurationEditObjectV1Request' is set
      if (SystemconfigurationEditObjectV1Request === undefined || SystemconfigurationEditObjectV1Request === null) {
        throw new Error("Missing the required parameter 'SystemconfigurationEditObjectV1Request' when calling systemconfigurationEditObjectV1");
      }

      let pathParams = {
        'pkiSystemconfigurationID': pkiSystemconfigurationID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SystemconfigurationEditObjectV1Response;
      return this.apiClient.callApi(
        '/1/object/systemconfiguration/{pkiSystemconfigurationID}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the systemconfigurationGetObjectV2 operation.
     * @callback module:eZmaxAPI/api/ObjectSystemconfigurationApi~systemconfigurationGetObjectV2Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/SystemconfigurationGetObjectV2Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve an existing Systemconfiguration
     * 
     * @param {Number} pkiSystemconfigurationID The unique ID of the Systemconfiguration
     * @param {module:eZmaxAPI/api/ObjectSystemconfigurationApi~systemconfigurationGetObjectV2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/SystemconfigurationGetObjectV2Response}
     */
    systemconfigurationGetObjectV2(pkiSystemconfigurationID, callback) {
      let postBody = null;
      // verify the required parameter 'pkiSystemconfigurationID' is set
      if (pkiSystemconfigurationID === undefined || pkiSystemconfigurationID === null) {
        throw new Error("Missing the required parameter 'pkiSystemconfigurationID' when calling systemconfigurationGetObjectV2");
      }

      let pathParams = {
        'pkiSystemconfigurationID': pkiSystemconfigurationID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SystemconfigurationGetObjectV2Response;
      return this.apiClient.callApi(
        '/2/object/systemconfiguration/{pkiSystemconfigurationID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
