/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommonResponseError from '../model/CommonResponseError';
import EzsigndiscussionCreateObjectV1Request from '../model/EzsigndiscussionCreateObjectV1Request';
import EzsigndiscussionCreateObjectV1Response from '../model/EzsigndiscussionCreateObjectV1Response';
import EzsigndiscussionDeleteObjectV1Response from '../model/EzsigndiscussionDeleteObjectV1Response';
import EzsigndiscussionGetObjectV2Response from '../model/EzsigndiscussionGetObjectV2Response';

/**
* ObjectEzsigndiscussion service.
* @module eZmaxAPI/api/ObjectEzsigndiscussionApi
* @version 1.2.0
*/
export default class ObjectEzsigndiscussionApi {

    /**
    * Constructs a new ObjectEzsigndiscussionApi. 
    * @alias module:eZmaxAPI/api/ObjectEzsigndiscussionApi
    * @class
    * @param {module:eZmaxAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:eZmaxAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the ezsigndiscussionCreateObjectV1 operation.
     * @callback module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionCreateObjectV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/EzsigndiscussionCreateObjectV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new Ezsigndiscussion
     * The endpoint allows to create one or many elements at once.
     * @param {module:eZmaxAPI/model/EzsigndiscussionCreateObjectV1Request} EzsigndiscussionCreateObjectV1Request 
     * @param {module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionCreateObjectV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/EzsigndiscussionCreateObjectV1Response}
     */
    ezsigndiscussionCreateObjectV1(EzsigndiscussionCreateObjectV1Request, callback) {
      let postBody = EzsigndiscussionCreateObjectV1Request;
      // verify the required parameter 'EzsigndiscussionCreateObjectV1Request' is set
      if (EzsigndiscussionCreateObjectV1Request === undefined || EzsigndiscussionCreateObjectV1Request === null) {
        throw new Error("Missing the required parameter 'EzsigndiscussionCreateObjectV1Request' when calling ezsigndiscussionCreateObjectV1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EzsigndiscussionCreateObjectV1Response;
      return this.apiClient.callApi(
        '/1/object/ezsigndiscussion', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the ezsigndiscussionDeleteObjectV1 operation.
     * @callback module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionDeleteObjectV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/EzsigndiscussionDeleteObjectV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an existing Ezsigndiscussion
     * 
     * @param {Number} pkiEzsigndiscussionID The unique ID of the Ezsigndiscussion
     * @param {module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionDeleteObjectV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/EzsigndiscussionDeleteObjectV1Response}
     */
    ezsigndiscussionDeleteObjectV1(pkiEzsigndiscussionID, callback) {
      let postBody = null;
      // verify the required parameter 'pkiEzsigndiscussionID' is set
      if (pkiEzsigndiscussionID === undefined || pkiEzsigndiscussionID === null) {
        throw new Error("Missing the required parameter 'pkiEzsigndiscussionID' when calling ezsigndiscussionDeleteObjectV1");
      }

      let pathParams = {
        'pkiEzsigndiscussionID': pkiEzsigndiscussionID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EzsigndiscussionDeleteObjectV1Response;
      return this.apiClient.callApi(
        '/1/object/ezsigndiscussion/{pkiEzsigndiscussionID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the ezsigndiscussionGetObjectV2 operation.
     * @callback module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionGetObjectV2Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/EzsigndiscussionGetObjectV2Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve an existing Ezsigndiscussion
     * 
     * @param {Number} pkiEzsigndiscussionID The unique ID of the Ezsigndiscussion
     * @param {module:eZmaxAPI/api/ObjectEzsigndiscussionApi~ezsigndiscussionGetObjectV2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/EzsigndiscussionGetObjectV2Response}
     */
    ezsigndiscussionGetObjectV2(pkiEzsigndiscussionID, callback) {
      let postBody = null;
      // verify the required parameter 'pkiEzsigndiscussionID' is set
      if (pkiEzsigndiscussionID === undefined || pkiEzsigndiscussionID === null) {
        throw new Error("Missing the required parameter 'pkiEzsigndiscussionID' when calling ezsigndiscussionGetObjectV2");
      }

      let pathParams = {
        'pkiEzsigndiscussionID': pkiEzsigndiscussionID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EzsigndiscussionGetObjectV2Response;
      return this.apiClient.callApi(
        '/2/object/ezsigndiscussion/{pkiEzsigndiscussionID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
