/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommunicationSendV1Request from '../model/CommunicationSendV1Request';
import CommunicationSendV1Response from '../model/CommunicationSendV1Response';

/**
* ObjectCommunication service.
* @module eZmaxAPI/api/ObjectCommunicationApi
* @version 1.2.0
*/
export default class ObjectCommunicationApi {

    /**
    * Constructs a new ObjectCommunicationApi. 
    * @alias module:eZmaxAPI/api/ObjectCommunicationApi
    * @class
    * @param {module:eZmaxAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:eZmaxAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the communicationSendV1 operation.
     * @callback module:eZmaxAPI/api/ObjectCommunicationApi~communicationSendV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/CommunicationSendV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a new Communication
     * The endpoint allows to send one or many elements at once.
     * @param {module:eZmaxAPI/model/CommunicationSendV1Request} CommunicationSendV1Request 
     * @param {module:eZmaxAPI/api/ObjectCommunicationApi~communicationSendV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/CommunicationSendV1Response}
     */
    communicationSendV1(CommunicationSendV1Request, callback) {
      let postBody = CommunicationSendV1Request;
      // verify the required parameter 'CommunicationSendV1Request' is set
      if (CommunicationSendV1Request === undefined || CommunicationSendV1Request === null) {
        throw new Error("Missing the required parameter 'CommunicationSendV1Request' when calling communicationSendV1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommunicationSendV1Response;
      return this.apiClient.callApi(
        '/1/object/communication/send', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
