/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommonResponseError from '../model/CommonResponseError';
import HeaderAcceptLanguage from '../model/HeaderAcceptLanguage';
import UserstagedCreateUserV1Response from '../model/UserstagedCreateUserV1Response';
import UserstagedDeleteObjectV1Response from '../model/UserstagedDeleteObjectV1Response';
import UserstagedGetListV1Response from '../model/UserstagedGetListV1Response';
import UserstagedGetObjectV2Response from '../model/UserstagedGetObjectV2Response';
import UserstagedMapV1Request from '../model/UserstagedMapV1Request';
import UserstagedMapV1Response from '../model/UserstagedMapV1Response';

/**
* ObjectUserstaged service.
* @module eZmaxAPI/api/ObjectUserstagedApi
* @version 1.1.18
*/
export default class ObjectUserstagedApi {

    /**
    * Constructs a new ObjectUserstagedApi. 
    * @alias module:eZmaxAPI/api/ObjectUserstagedApi
    * @class
    * @param {module:eZmaxAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:eZmaxAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the userstagedCreateUserV1 operation.
     * @callback module:eZmaxAPI/api/ObjectUserstagedApi~userstagedCreateUserV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/UserstagedCreateUserV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a User from a Userstaged and then map it
     * Default values will be used while creating the User. If you need to change those values, you should use the route to edit a User.
     * @param {Number} pkiUserstagedID 
     * @param {Object.<String, Object>} body 
     * @param {module:eZmaxAPI/api/ObjectUserstagedApi~userstagedCreateUserV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/UserstagedCreateUserV1Response}
     */
    userstagedCreateUserV1(pkiUserstagedID, body, callback) {
      let postBody = body;
      // verify the required parameter 'pkiUserstagedID' is set
      if (pkiUserstagedID === undefined || pkiUserstagedID === null) {
        throw new Error("Missing the required parameter 'pkiUserstagedID' when calling userstagedCreateUserV1");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling userstagedCreateUserV1");
      }

      let pathParams = {
        'pkiUserstagedID': pkiUserstagedID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserstagedCreateUserV1Response;
      return this.apiClient.callApi(
        '/1/object/userstaged/{pkiUserstagedID}/createUser', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the userstagedDeleteObjectV1 operation.
     * @callback module:eZmaxAPI/api/ObjectUserstagedApi~userstagedDeleteObjectV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/UserstagedDeleteObjectV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an existing Userstaged
     * 
     * @param {Number} pkiUserstagedID 
     * @param {module:eZmaxAPI/api/ObjectUserstagedApi~userstagedDeleteObjectV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/UserstagedDeleteObjectV1Response}
     */
    userstagedDeleteObjectV1(pkiUserstagedID, callback) {
      let postBody = null;
      // verify the required parameter 'pkiUserstagedID' is set
      if (pkiUserstagedID === undefined || pkiUserstagedID === null) {
        throw new Error("Missing the required parameter 'pkiUserstagedID' when calling userstagedDeleteObjectV1");
      }

      let pathParams = {
        'pkiUserstagedID': pkiUserstagedID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserstagedDeleteObjectV1Response;
      return this.apiClient.callApi(
        '/1/object/userstaged/{pkiUserstagedID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the userstagedGetListV1 operation.
     * @callback module:eZmaxAPI/api/ObjectUserstagedApi~userstagedGetListV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/UserstagedGetListV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve Userstaged list
     * 
     * @param {Object} opts Optional parameters
     * @param {module:eZmaxAPI/model/String} [eOrderBy] Specify how you want the results to be sorted
     * @param {Number} [iRowMax = 10000)] 
     * @param {Number} [iRowOffset = 0)] 
     * @param {module:eZmaxAPI/model/HeaderAcceptLanguage} [Accept_Language] 
     * @param {String} [sFilter] 
     * @param {module:eZmaxAPI/api/ObjectUserstagedApi~userstagedGetListV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/UserstagedGetListV1Response}
     */
    userstagedGetListV1(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'eOrderBy': opts['eOrderBy'],
        'iRowMax': opts['iRowMax'],
        'iRowOffset': opts['iRowOffset'],
        'sFilter': opts['sFilter']
      };
      let headerParams = {
        'Accept-Language': opts['Accept_Language']
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];
      let returnType = UserstagedGetListV1Response;
      return this.apiClient.callApi(
        '/1/object/userstaged/getList', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the userstagedGetObjectV2 operation.
     * @callback module:eZmaxAPI/api/ObjectUserstagedApi~userstagedGetObjectV2Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/UserstagedGetObjectV2Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve an existing Userstaged
     * 
     * @param {Number} pkiUserstagedID 
     * @param {module:eZmaxAPI/api/ObjectUserstagedApi~userstagedGetObjectV2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/UserstagedGetObjectV2Response}
     */
    userstagedGetObjectV2(pkiUserstagedID, callback) {
      let postBody = null;
      // verify the required parameter 'pkiUserstagedID' is set
      if (pkiUserstagedID === undefined || pkiUserstagedID === null) {
        throw new Error("Missing the required parameter 'pkiUserstagedID' when calling userstagedGetObjectV2");
      }

      let pathParams = {
        'pkiUserstagedID': pkiUserstagedID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserstagedGetObjectV2Response;
      return this.apiClient.callApi(
        '/2/object/userstaged/{pkiUserstagedID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the userstagedMapV1 operation.
     * @callback module:eZmaxAPI/api/ObjectUserstagedApi~userstagedMapV1Callback
     * @param {String} error Error message, if any.
     * @param {module:eZmaxAPI/model/UserstagedMapV1Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Map the Userstaged to an existing user
     * 
     * @param {Number} pkiUserstagedID 
     * @param {module:eZmaxAPI/model/UserstagedMapV1Request} UserstagedMapV1Request 
     * @param {module:eZmaxAPI/api/ObjectUserstagedApi~userstagedMapV1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:eZmaxAPI/model/UserstagedMapV1Response}
     */
    userstagedMapV1(pkiUserstagedID, UserstagedMapV1Request, callback) {
      let postBody = UserstagedMapV1Request;
      // verify the required parameter 'pkiUserstagedID' is set
      if (pkiUserstagedID === undefined || pkiUserstagedID === null) {
        throw new Error("Missing the required parameter 'pkiUserstagedID' when calling userstagedMapV1");
      }
      // verify the required parameter 'UserstagedMapV1Request' is set
      if (UserstagedMapV1Request === undefined || UserstagedMapV1Request === null) {
        throw new Error("Missing the required parameter 'UserstagedMapV1Request' when calling userstagedMapV1");
      }

      let pathParams = {
        'pkiUserstagedID': pkiUserstagedID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserstagedMapV1Response;
      return this.apiClient.callApi(
        '/1/object/userstaged/{pkiUserstagedID}/map', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
