/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApikeyResponse from './ApikeyResponse';
import CommonAudit from './CommonAudit';
import MultilingualApikeyDescription from './MultilingualApikeyDescription';

/**
 * The ApikeyResponseCompound model module.
 * @module eZmaxAPI/model/ApikeyResponseCompound
 * @version 1.1.18
 */
class ApikeyResponseCompound {
    /**
     * Constructs a new <code>ApikeyResponseCompound</code>.
     * An Apikey Object and children to create a complete structure
     * @alias module:eZmaxAPI/model/ApikeyResponseCompound
     * @implements module:eZmaxAPI/model/ApikeyResponse
     * @param pkiApikeyID {Number} The unique ID of the Apikey
     * @param fkiUserID {Number} The unique ID of the User
     * @param objApikeyDescription {module:eZmaxAPI/model/MultilingualApikeyDescription} 
     * @param bApikeyIsactive {Boolean} Whether the apikey is active or not
     * @param objAudit {module:eZmaxAPI/model/CommonAudit} 
     */
    constructor(pkiApikeyID, fkiUserID, objApikeyDescription, bApikeyIsactive, objAudit) { 
        ApikeyResponse.initialize(this, pkiApikeyID, fkiUserID, objApikeyDescription, bApikeyIsactive, objAudit);
        ApikeyResponseCompound.initialize(this, pkiApikeyID, fkiUserID, objApikeyDescription, bApikeyIsactive, objAudit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pkiApikeyID, fkiUserID, objApikeyDescription, bApikeyIsactive, objAudit) { 
        obj['pkiApikeyID'] = pkiApikeyID;
        obj['fkiUserID'] = fkiUserID;
        obj['objApikeyDescription'] = objApikeyDescription;
        obj['bApikeyIsactive'] = bApikeyIsactive;
        obj['objAudit'] = objAudit;
    }

    /**
     * Constructs a <code>ApikeyResponseCompound</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/ApikeyResponseCompound} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/ApikeyResponseCompound} The populated <code>ApikeyResponseCompound</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApikeyResponseCompound();
            ApikeyResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('pkiApikeyID')) {
                obj['pkiApikeyID'] = ApiClient.convertToType(data['pkiApikeyID'], 'Number');
            }
            if (data.hasOwnProperty('fkiUserID')) {
                obj['fkiUserID'] = ApiClient.convertToType(data['fkiUserID'], 'Number');
            }
            if (data.hasOwnProperty('objApikeyDescription')) {
                obj['objApikeyDescription'] = MultilingualApikeyDescription.constructFromObject(data['objApikeyDescription']);
            }
            if (data.hasOwnProperty('sComputedToken')) {
                obj['sComputedToken'] = ApiClient.convertToType(data['sComputedToken'], 'String');
            }
            if (data.hasOwnProperty('bApikeyIsactive')) {
                obj['bApikeyIsactive'] = ApiClient.convertToType(data['bApikeyIsactive'], 'Boolean');
            }
            if (data.hasOwnProperty('objAudit')) {
                obj['objAudit'] = CommonAudit.constructFromObject(data['objAudit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApikeyResponseCompound</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApikeyResponseCompound</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApikeyResponseCompound.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `objApikeyDescription`
        if (data['objApikeyDescription']) { // data not null
          MultilingualApikeyDescription.validateJSON(data['objApikeyDescription']);
        }
        // ensure the json data is a string
        if (data['sComputedToken'] && !(typeof data['sComputedToken'] === 'string' || data['sComputedToken'] instanceof String)) {
            throw new Error("Expected the field `sComputedToken` to be a primitive type in the JSON string but got " + data['sComputedToken']);
        }
        // validate the optional field `objAudit`
        if (data['objAudit']) { // data not null
          CommonAudit.validateJSON(data['objAudit']);
        }

        return true;
    }

/**
     * Returns The unique ID of the Apikey
     * minimum: 0
     * @return {Number}
     */
    getPkiApikeyID() {
        return this.pkiApikeyID;
    }

    /**
     * Sets The unique ID of the Apikey
     * @param {Number} pkiApikeyID The unique ID of the Apikey
     */
    setPkiApikeyID(pkiApikeyID) {
        this['pkiApikeyID'] = pkiApikeyID;
    }
/**
     * Returns The unique ID of the User
     * minimum: 0
     * @return {Number}
     */
    getFkiUserID() {
        return this.fkiUserID;
    }

    /**
     * Sets The unique ID of the User
     * @param {Number} fkiUserID The unique ID of the User
     */
    setFkiUserID(fkiUserID) {
        this['fkiUserID'] = fkiUserID;
    }
/**
     * @return {module:eZmaxAPI/model/MultilingualApikeyDescription}
     */
    getObjApikeyDescription() {
        return this.objApikeyDescription;
    }

    /**
     * @param {module:eZmaxAPI/model/MultilingualApikeyDescription} objApikeyDescription
     */
    setObjApikeyDescription(objApikeyDescription) {
        this['objApikeyDescription'] = objApikeyDescription;
    }
/**
     * Returns The secret token for the API key.  This will be returned only on creation.
     * @return {String}
     */
    getSComputedToken() {
        return this.sComputedToken;
    }

    /**
     * Sets The secret token for the API key.  This will be returned only on creation.
     * @param {String} sComputedToken The secret token for the API key.  This will be returned only on creation.
     */
    setSComputedToken(sComputedToken) {
        this['sComputedToken'] = sComputedToken;
    }
/**
     * Returns Whether the apikey is active or not
     * @return {Boolean}
     */
    getBApikeyIsactive() {
        return this.bApikeyIsactive;
    }

    /**
     * Sets Whether the apikey is active or not
     * @param {Boolean} bApikeyIsactive Whether the apikey is active or not
     */
    setBApikeyIsactive(bApikeyIsactive) {
        this['bApikeyIsactive'] = bApikeyIsactive;
    }
/**
     * @return {module:eZmaxAPI/model/CommonAudit}
     */
    getObjAudit() {
        return this.objAudit;
    }

    /**
     * @param {module:eZmaxAPI/model/CommonAudit} objAudit
     */
    setObjAudit(objAudit) {
        this['objAudit'] = objAudit;
    }

}

ApikeyResponseCompound.RequiredProperties = ["pkiApikeyID", "fkiUserID", "objApikeyDescription", "bApikeyIsactive", "objAudit"];

/**
 * The unique ID of the Apikey
 * @member {Number} pkiApikeyID
 */
ApikeyResponseCompound.prototype['pkiApikeyID'] = undefined;

/**
 * The unique ID of the User
 * @member {Number} fkiUserID
 */
ApikeyResponseCompound.prototype['fkiUserID'] = undefined;

/**
 * @member {module:eZmaxAPI/model/MultilingualApikeyDescription} objApikeyDescription
 */
ApikeyResponseCompound.prototype['objApikeyDescription'] = undefined;

/**
 * The secret token for the API key.  This will be returned only on creation.
 * @member {String} sComputedToken
 */
ApikeyResponseCompound.prototype['sComputedToken'] = undefined;

/**
 * Whether the apikey is active or not
 * @member {Boolean} bApikeyIsactive
 */
ApikeyResponseCompound.prototype['bApikeyIsactive'] = undefined;

/**
 * @member {module:eZmaxAPI/model/CommonAudit} objAudit
 */
ApikeyResponseCompound.prototype['objAudit'] = undefined;


// Implement ApikeyResponse interface:
/**
 * The unique ID of the Apikey
 * @member {Number} pkiApikeyID
 */
ApikeyResponse.prototype['pkiApikeyID'] = undefined;
/**
 * The unique ID of the User
 * @member {Number} fkiUserID
 */
ApikeyResponse.prototype['fkiUserID'] = undefined;
/**
 * @member {module:eZmaxAPI/model/MultilingualApikeyDescription} objApikeyDescription
 */
ApikeyResponse.prototype['objApikeyDescription'] = undefined;
/**
 * The secret token for the API key.  This will be returned only on creation.
 * @member {String} sComputedToken
 */
ApikeyResponse.prototype['sComputedToken'] = undefined;
/**
 * Whether the apikey is active or not
 * @member {Boolean} bApikeyIsactive
 */
ApikeyResponse.prototype['bApikeyIsactive'] = undefined;
/**
 * @member {module:eZmaxAPI/model/CommonAudit} objAudit
 */
ApikeyResponse.prototype['objAudit'] = undefined;




export default ApikeyResponseCompound;

