/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommunicationexternalimageResponse from './CommunicationexternalimageResponse';

/**
 * The CommunicationexternalimageResponseCompound model module.
 * @module eZmaxAPI/model/CommunicationexternalimageResponseCompound
 * @version 1.1.17
 */
class CommunicationexternalimageResponseCompound {
    /**
     * Constructs a new <code>CommunicationexternalimageResponseCompound</code>.
     * A Communicationexternalimage Object
     * @alias module:eZmaxAPI/model/CommunicationexternalimageResponseCompound
     * @implements module:eZmaxAPI/model/CommunicationexternalimageResponse
     * @param pkiCommunicationexternalimageID {Number} The unique ID of the Communicationexternalimage
     * @param sCommunicationexternalimageMD5 {String} MD5 Hash of the Communicationexternalimage.
     */
    constructor(pkiCommunicationexternalimageID, sCommunicationexternalimageMD5) { 
        CommunicationexternalimageResponse.initialize(this, pkiCommunicationexternalimageID, sCommunicationexternalimageMD5);
        CommunicationexternalimageResponseCompound.initialize(this, pkiCommunicationexternalimageID, sCommunicationexternalimageMD5);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pkiCommunicationexternalimageID, sCommunicationexternalimageMD5) { 
        obj['pkiCommunicationexternalimageID'] = pkiCommunicationexternalimageID;
        obj['sCommunicationexternalimageMD5'] = sCommunicationexternalimageMD5;
    }

    /**
     * Constructs a <code>CommunicationexternalimageResponseCompound</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/CommunicationexternalimageResponseCompound} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/CommunicationexternalimageResponseCompound} The populated <code>CommunicationexternalimageResponseCompound</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommunicationexternalimageResponseCompound();
            CommunicationexternalimageResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('pkiCommunicationexternalimageID')) {
                obj['pkiCommunicationexternalimageID'] = ApiClient.convertToType(data['pkiCommunicationexternalimageID'], 'Number');
            }
            if (data.hasOwnProperty('sCommunicationexternalimageMD5')) {
                obj['sCommunicationexternalimageMD5'] = ApiClient.convertToType(data['sCommunicationexternalimageMD5'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CommunicationexternalimageResponseCompound</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CommunicationexternalimageResponseCompound</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CommunicationexternalimageResponseCompound.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['sCommunicationexternalimageMD5'] && !(typeof data['sCommunicationexternalimageMD5'] === 'string' || data['sCommunicationexternalimageMD5'] instanceof String)) {
            throw new Error("Expected the field `sCommunicationexternalimageMD5` to be a primitive type in the JSON string but got " + data['sCommunicationexternalimageMD5']);
        }

        return true;
    }

/**
     * Returns The unique ID of the Communicationexternalimage
     * @return {Number}
     */
    getPkiCommunicationexternalimageID() {
        return this.pkiCommunicationexternalimageID;
    }

    /**
     * Sets The unique ID of the Communicationexternalimage
     * @param {Number} pkiCommunicationexternalimageID The unique ID of the Communicationexternalimage
     */
    setPkiCommunicationexternalimageID(pkiCommunicationexternalimageID) {
        this['pkiCommunicationexternalimageID'] = pkiCommunicationexternalimageID;
    }
/**
     * Returns MD5 Hash of the Communicationexternalimage.
     * @return {String}
     */
    getSCommunicationexternalimageMD5() {
        return this.sCommunicationexternalimageMD5;
    }

    /**
     * Sets MD5 Hash of the Communicationexternalimage.
     * @param {String} sCommunicationexternalimageMD5 MD5 Hash of the Communicationexternalimage.
     */
    setSCommunicationexternalimageMD5(sCommunicationexternalimageMD5) {
        this['sCommunicationexternalimageMD5'] = sCommunicationexternalimageMD5;
    }

}

CommunicationexternalimageResponseCompound.RequiredProperties = ["pkiCommunicationexternalimageID", "sCommunicationexternalimageMD5"];

/**
 * The unique ID of the Communicationexternalimage
 * @member {Number} pkiCommunicationexternalimageID
 */
CommunicationexternalimageResponseCompound.prototype['pkiCommunicationexternalimageID'] = undefined;

/**
 * MD5 Hash of the Communicationexternalimage.
 * @member {String} sCommunicationexternalimageMD5
 */
CommunicationexternalimageResponseCompound.prototype['sCommunicationexternalimageMD5'] = undefined;


// Implement CommunicationexternalimageResponse interface:
/**
 * The unique ID of the Communicationexternalimage
 * @member {Number} pkiCommunicationexternalimageID
 */
CommunicationexternalimageResponse.prototype['pkiCommunicationexternalimageID'] = undefined;
/**
 * MD5 Hash of the Communicationexternalimage.
 * @member {String} sCommunicationexternalimageMD5
 */
CommunicationexternalimageResponse.prototype['sCommunicationexternalimageMD5'] = undefined;




export default CommunicationexternalimageResponseCompound;

