/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldEEzsignsignatureType from './FieldEEzsignsignatureType';

/**
 * The CustomEzsignsignatureEzsignsignaturesAutomaticResponse model module.
 * @module eZmaxAPI/model/CustomEzsignsignatureEzsignsignaturesAutomaticResponse
 * @version 1.2.0
 */
class CustomEzsignsignatureEzsignsignaturesAutomaticResponse {
    /**
     * Constructs a new <code>CustomEzsignsignatureEzsignsignaturesAutomaticResponse</code>.
     * An Ezsignsignature Object in the context of an EzsignsignaturesAutomatic path
     * @alias module:eZmaxAPI/model/CustomEzsignsignatureEzsignsignaturesAutomaticResponse
     * @param pkiEzsignsignatureID {Number} The unique ID of the Ezsignsignature
     * @param eEzsignsignatureType {module:eZmaxAPI/model/FieldEEzsignsignatureType} 
     * @param iEzsignpagePagenumber {Number} The page number in the Ezsigndocument
     */
    constructor(pkiEzsignsignatureID, eEzsignsignatureType, iEzsignpagePagenumber) { 
        
        CustomEzsignsignatureEzsignsignaturesAutomaticResponse.initialize(this, pkiEzsignsignatureID, eEzsignsignatureType, iEzsignpagePagenumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pkiEzsignsignatureID, eEzsignsignatureType, iEzsignpagePagenumber) { 
        obj['pkiEzsignsignatureID'] = pkiEzsignsignatureID;
        obj['eEzsignsignatureType'] = eEzsignsignatureType;
        obj['iEzsignpagePagenumber'] = iEzsignpagePagenumber;
    }

    /**
     * Constructs a <code>CustomEzsignsignatureEzsignsignaturesAutomaticResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/CustomEzsignsignatureEzsignsignaturesAutomaticResponse} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/CustomEzsignsignatureEzsignsignaturesAutomaticResponse} The populated <code>CustomEzsignsignatureEzsignsignaturesAutomaticResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomEzsignsignatureEzsignsignaturesAutomaticResponse();

            if (data.hasOwnProperty('pkiEzsignsignatureID')) {
                obj['pkiEzsignsignatureID'] = ApiClient.convertToType(data['pkiEzsignsignatureID'], 'Number');
            }
            if (data.hasOwnProperty('eEzsignsignatureType')) {
                obj['eEzsignsignatureType'] = FieldEEzsignsignatureType.constructFromObject(data['eEzsignsignatureType']);
            }
            if (data.hasOwnProperty('iEzsignpagePagenumber')) {
                obj['iEzsignpagePagenumber'] = ApiClient.convertToType(data['iEzsignpagePagenumber'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomEzsignsignatureEzsignsignaturesAutomaticResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomEzsignsignatureEzsignsignaturesAutomaticResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomEzsignsignatureEzsignsignaturesAutomaticResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * Returns The unique ID of the Ezsignsignature
     * minimum: 0
     * @return {Number}
     */
    getPkiEzsignsignatureID() {
        return this.pkiEzsignsignatureID;
    }

    /**
     * Sets The unique ID of the Ezsignsignature
     * @param {Number} pkiEzsignsignatureID The unique ID of the Ezsignsignature
     */
    setPkiEzsignsignatureID(pkiEzsignsignatureID) {
        this['pkiEzsignsignatureID'] = pkiEzsignsignatureID;
    }
/**
     * @return {module:eZmaxAPI/model/FieldEEzsignsignatureType}
     */
    getEEzsignsignatureType() {
        return this.eEzsignsignatureType;
    }

    /**
     * @param {module:eZmaxAPI/model/FieldEEzsignsignatureType} eEzsignsignatureType
     */
    setEEzsignsignatureType(eEzsignsignatureType) {
        this['eEzsignsignatureType'] = eEzsignsignatureType;
    }
/**
     * Returns The page number in the Ezsigndocument
     * minimum: 1
     * @return {Number}
     */
    getIEzsignpagePagenumber() {
        return this.iEzsignpagePagenumber;
    }

    /**
     * Sets The page number in the Ezsigndocument
     * @param {Number} iEzsignpagePagenumber The page number in the Ezsigndocument
     */
    setIEzsignpagePagenumber(iEzsignpagePagenumber) {
        this['iEzsignpagePagenumber'] = iEzsignpagePagenumber;
    }

}

CustomEzsignsignatureEzsignsignaturesAutomaticResponse.RequiredProperties = ["pkiEzsignsignatureID", "eEzsignsignatureType", "iEzsignpagePagenumber"];

/**
 * The unique ID of the Ezsignsignature
 * @member {Number} pkiEzsignsignatureID
 */
CustomEzsignsignatureEzsignsignaturesAutomaticResponse.prototype['pkiEzsignsignatureID'] = undefined;

/**
 * @member {module:eZmaxAPI/model/FieldEEzsignsignatureType} eEzsignsignatureType
 */
CustomEzsignsignatureEzsignsignaturesAutomaticResponse.prototype['eEzsignsignatureType'] = undefined;

/**
 * The page number in the Ezsigndocument
 * @member {Number} iEzsignpagePagenumber
 */
CustomEzsignsignatureEzsignsignaturesAutomaticResponse.prototype['iEzsignpagePagenumber'] = undefined;






export default CustomEzsignsignatureEzsignsignaturesAutomaticResponse;

