/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputedECommunicationDirection from './ComputedECommunicationDirection';
import FieldECommunicationImportance from './FieldECommunicationImportance';
import FieldECommunicationType from './FieldECommunicationType';

/**
 * The CustomCommunicationListElementResponse model module.
 * @module eZmaxAPI/model/CustomCommunicationListElementResponse
 * @version 1.1.18
 */
class CustomCommunicationListElementResponse {
    /**
     * Constructs a new <code>CustomCommunicationListElementResponse</code>.
     * A Communication List Element
     * @alias module:eZmaxAPI/model/CustomCommunicationListElementResponse
     * @param pkiCommunicationID {Number} The unique ID of the Communication.
     * @param dtCreatedDate {String} The date and time at which the object was created
     * @param eCommunicationDirection {module:eZmaxAPI/model/ComputedECommunicationDirection} 
     * @param eCommunicationImportance {module:eZmaxAPI/model/FieldECommunicationImportance} 
     * @param eCommunicationType {module:eZmaxAPI/model/FieldECommunicationType} 
     * @param iCommunicationrecipientCount {Number} The count of Communicationrecipient
     * @param sCommunicationSubject {String} The subject of the Communication
     * @param sCommunicationSender {String} The sender name of the Communication
     * @param sCommunicationRecipient {String} The recipients' name of the Communication
     */
    constructor(pkiCommunicationID, dtCreatedDate, eCommunicationDirection, eCommunicationImportance, eCommunicationType, iCommunicationrecipientCount, sCommunicationSubject, sCommunicationSender, sCommunicationRecipient) { 
        
        CustomCommunicationListElementResponse.initialize(this, pkiCommunicationID, dtCreatedDate, eCommunicationDirection, eCommunicationImportance, eCommunicationType, iCommunicationrecipientCount, sCommunicationSubject, sCommunicationSender, sCommunicationRecipient);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pkiCommunicationID, dtCreatedDate, eCommunicationDirection, eCommunicationImportance, eCommunicationType, iCommunicationrecipientCount, sCommunicationSubject, sCommunicationSender, sCommunicationRecipient) { 
        obj['pkiCommunicationID'] = pkiCommunicationID;
        obj['dtCreatedDate'] = dtCreatedDate;
        obj['eCommunicationDirection'] = eCommunicationDirection;
        obj['eCommunicationImportance'] = eCommunicationImportance;
        obj['eCommunicationType'] = eCommunicationType;
        obj['iCommunicationrecipientCount'] = iCommunicationrecipientCount;
        obj['sCommunicationSubject'] = sCommunicationSubject;
        obj['sCommunicationSender'] = sCommunicationSender;
        obj['sCommunicationRecipient'] = sCommunicationRecipient;
    }

    /**
     * Constructs a <code>CustomCommunicationListElementResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/CustomCommunicationListElementResponse} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/CustomCommunicationListElementResponse} The populated <code>CustomCommunicationListElementResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomCommunicationListElementResponse();

            if (data.hasOwnProperty('pkiCommunicationID')) {
                obj['pkiCommunicationID'] = ApiClient.convertToType(data['pkiCommunicationID'], 'Number');
            }
            if (data.hasOwnProperty('dtCreatedDate')) {
                obj['dtCreatedDate'] = ApiClient.convertToType(data['dtCreatedDate'], 'String');
            }
            if (data.hasOwnProperty('eCommunicationDirection')) {
                obj['eCommunicationDirection'] = ComputedECommunicationDirection.constructFromObject(data['eCommunicationDirection']);
            }
            if (data.hasOwnProperty('eCommunicationImportance')) {
                obj['eCommunicationImportance'] = FieldECommunicationImportance.constructFromObject(data['eCommunicationImportance']);
            }
            if (data.hasOwnProperty('eCommunicationType')) {
                obj['eCommunicationType'] = FieldECommunicationType.constructFromObject(data['eCommunicationType']);
            }
            if (data.hasOwnProperty('iCommunicationrecipientCount')) {
                obj['iCommunicationrecipientCount'] = ApiClient.convertToType(data['iCommunicationrecipientCount'], 'Number');
            }
            if (data.hasOwnProperty('sCommunicationSubject')) {
                obj['sCommunicationSubject'] = ApiClient.convertToType(data['sCommunicationSubject'], 'String');
            }
            if (data.hasOwnProperty('sCommunicationSender')) {
                obj['sCommunicationSender'] = ApiClient.convertToType(data['sCommunicationSender'], 'String');
            }
            if (data.hasOwnProperty('sCommunicationRecipient')) {
                obj['sCommunicationRecipient'] = ApiClient.convertToType(data['sCommunicationRecipient'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomCommunicationListElementResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomCommunicationListElementResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomCommunicationListElementResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dtCreatedDate'] && !(typeof data['dtCreatedDate'] === 'string' || data['dtCreatedDate'] instanceof String)) {
            throw new Error("Expected the field `dtCreatedDate` to be a primitive type in the JSON string but got " + data['dtCreatedDate']);
        }
        // ensure the json data is a string
        if (data['sCommunicationSubject'] && !(typeof data['sCommunicationSubject'] === 'string' || data['sCommunicationSubject'] instanceof String)) {
            throw new Error("Expected the field `sCommunicationSubject` to be a primitive type in the JSON string but got " + data['sCommunicationSubject']);
        }
        // ensure the json data is a string
        if (data['sCommunicationSender'] && !(typeof data['sCommunicationSender'] === 'string' || data['sCommunicationSender'] instanceof String)) {
            throw new Error("Expected the field `sCommunicationSender` to be a primitive type in the JSON string but got " + data['sCommunicationSender']);
        }
        // ensure the json data is a string
        if (data['sCommunicationRecipient'] && !(typeof data['sCommunicationRecipient'] === 'string' || data['sCommunicationRecipient'] instanceof String)) {
            throw new Error("Expected the field `sCommunicationRecipient` to be a primitive type in the JSON string but got " + data['sCommunicationRecipient']);
        }

        return true;
    }

/**
     * Returns The unique ID of the Communication.
     * minimum: 0
     * @return {Number}
     */
    getPkiCommunicationID() {
        return this.pkiCommunicationID;
    }

    /**
     * Sets The unique ID of the Communication.
     * @param {Number} pkiCommunicationID The unique ID of the Communication.
     */
    setPkiCommunicationID(pkiCommunicationID) {
        this['pkiCommunicationID'] = pkiCommunicationID;
    }
/**
     * Returns The date and time at which the object was created
     * @return {String}
     */
    getDtCreatedDate() {
        return this.dtCreatedDate;
    }

    /**
     * Sets The date and time at which the object was created
     * @param {String} dtCreatedDate The date and time at which the object was created
     */
    setDtCreatedDate(dtCreatedDate) {
        this['dtCreatedDate'] = dtCreatedDate;
    }
/**
     * @return {module:eZmaxAPI/model/ComputedECommunicationDirection}
     */
    getECommunicationDirection() {
        return this.eCommunicationDirection;
    }

    /**
     * @param {module:eZmaxAPI/model/ComputedECommunicationDirection} eCommunicationDirection
     */
    setECommunicationDirection(eCommunicationDirection) {
        this['eCommunicationDirection'] = eCommunicationDirection;
    }
/**
     * @return {module:eZmaxAPI/model/FieldECommunicationImportance}
     */
    getECommunicationImportance() {
        return this.eCommunicationImportance;
    }

    /**
     * @param {module:eZmaxAPI/model/FieldECommunicationImportance} eCommunicationImportance
     */
    setECommunicationImportance(eCommunicationImportance) {
        this['eCommunicationImportance'] = eCommunicationImportance;
    }
/**
     * @return {module:eZmaxAPI/model/FieldECommunicationType}
     */
    getECommunicationType() {
        return this.eCommunicationType;
    }

    /**
     * @param {module:eZmaxAPI/model/FieldECommunicationType} eCommunicationType
     */
    setECommunicationType(eCommunicationType) {
        this['eCommunicationType'] = eCommunicationType;
    }
/**
     * Returns The count of Communicationrecipient
     * @return {Number}
     */
    getICommunicationrecipientCount() {
        return this.iCommunicationrecipientCount;
    }

    /**
     * Sets The count of Communicationrecipient
     * @param {Number} iCommunicationrecipientCount The count of Communicationrecipient
     */
    setICommunicationrecipientCount(iCommunicationrecipientCount) {
        this['iCommunicationrecipientCount'] = iCommunicationrecipientCount;
    }
/**
     * Returns The subject of the Communication
     * @return {String}
     */
    getSCommunicationSubject() {
        return this.sCommunicationSubject;
    }

    /**
     * Sets The subject of the Communication
     * @param {String} sCommunicationSubject The subject of the Communication
     */
    setSCommunicationSubject(sCommunicationSubject) {
        this['sCommunicationSubject'] = sCommunicationSubject;
    }
/**
     * Returns The sender name of the Communication
     * @return {String}
     */
    getSCommunicationSender() {
        return this.sCommunicationSender;
    }

    /**
     * Sets The sender name of the Communication
     * @param {String} sCommunicationSender The sender name of the Communication
     */
    setSCommunicationSender(sCommunicationSender) {
        this['sCommunicationSender'] = sCommunicationSender;
    }
/**
     * Returns The recipients' name of the Communication
     * @return {String}
     */
    getSCommunicationRecipient() {
        return this.sCommunicationRecipient;
    }

    /**
     * Sets The recipients' name of the Communication
     * @param {String} sCommunicationRecipient The recipients' name of the Communication
     */
    setSCommunicationRecipient(sCommunicationRecipient) {
        this['sCommunicationRecipient'] = sCommunicationRecipient;
    }

}

CustomCommunicationListElementResponse.RequiredProperties = ["pkiCommunicationID", "dtCreatedDate", "eCommunicationDirection", "eCommunicationImportance", "eCommunicationType", "iCommunicationrecipientCount", "sCommunicationSubject", "sCommunicationSender", "sCommunicationRecipient"];

/**
 * The unique ID of the Communication.
 * @member {Number} pkiCommunicationID
 */
CustomCommunicationListElementResponse.prototype['pkiCommunicationID'] = undefined;

/**
 * The date and time at which the object was created
 * @member {String} dtCreatedDate
 */
CustomCommunicationListElementResponse.prototype['dtCreatedDate'] = undefined;

/**
 * @member {module:eZmaxAPI/model/ComputedECommunicationDirection} eCommunicationDirection
 */
CustomCommunicationListElementResponse.prototype['eCommunicationDirection'] = undefined;

/**
 * @member {module:eZmaxAPI/model/FieldECommunicationImportance} eCommunicationImportance
 */
CustomCommunicationListElementResponse.prototype['eCommunicationImportance'] = undefined;

/**
 * @member {module:eZmaxAPI/model/FieldECommunicationType} eCommunicationType
 */
CustomCommunicationListElementResponse.prototype['eCommunicationType'] = undefined;

/**
 * The count of Communicationrecipient
 * @member {Number} iCommunicationrecipientCount
 */
CustomCommunicationListElementResponse.prototype['iCommunicationrecipientCount'] = undefined;

/**
 * The subject of the Communication
 * @member {String} sCommunicationSubject
 */
CustomCommunicationListElementResponse.prototype['sCommunicationSubject'] = undefined;

/**
 * The sender name of the Communication
 * @member {String} sCommunicationSender
 */
CustomCommunicationListElementResponse.prototype['sCommunicationSender'] = undefined;

/**
 * The recipients' name of the Communication
 * @member {String} sCommunicationRecipient
 */
CustomCommunicationListElementResponse.prototype['sCommunicationRecipient'] = undefined;






export default CustomCommunicationListElementResponse;

