/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EzsigntemplateRequestCompoundV2 from './EzsigntemplateRequestCompoundV2';

/**
 * The EzsigntemplateEditObjectV2Request model module.
 * @module eZmaxAPI/model/EzsigntemplateEditObjectV2Request
 * @version 1.2.0
 */
class EzsigntemplateEditObjectV2Request {
    /**
     * Constructs a new <code>EzsigntemplateEditObjectV2Request</code>.
     * Request for PUT /2/object/ezsigntemplate/{pkiEzsigntemplateID}
     * @alias module:eZmaxAPI/model/EzsigntemplateEditObjectV2Request
     * @param objEzsigntemplate {module:eZmaxAPI/model/EzsigntemplateRequestCompoundV2} 
     */
    constructor(objEzsigntemplate) { 
        
        EzsigntemplateEditObjectV2Request.initialize(this, objEzsigntemplate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objEzsigntemplate) { 
        obj['objEzsigntemplate'] = objEzsigntemplate;
    }

    /**
     * Constructs a <code>EzsigntemplateEditObjectV2Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/EzsigntemplateEditObjectV2Request} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/EzsigntemplateEditObjectV2Request} The populated <code>EzsigntemplateEditObjectV2Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EzsigntemplateEditObjectV2Request();

            if (data.hasOwnProperty('objEzsigntemplate')) {
                obj['objEzsigntemplate'] = EzsigntemplateRequestCompoundV2.constructFromObject(data['objEzsigntemplate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EzsigntemplateEditObjectV2Request</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EzsigntemplateEditObjectV2Request</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EzsigntemplateEditObjectV2Request.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `objEzsigntemplate`
        if (data['objEzsigntemplate']) { // data not null
          EzsigntemplateRequestCompoundV2.validateJSON(data['objEzsigntemplate']);
        }

        return true;
    }

/**
     * @return {module:eZmaxAPI/model/EzsigntemplateRequestCompoundV2}
     */
    getObjEzsigntemplate() {
        return this.objEzsigntemplate;
    }

    /**
     * @param {module:eZmaxAPI/model/EzsigntemplateRequestCompoundV2} objEzsigntemplate
     */
    setObjEzsigntemplate(objEzsigntemplate) {
        this['objEzsigntemplate'] = objEzsigntemplate;
    }

}

EzsigntemplateEditObjectV2Request.RequiredProperties = ["objEzsigntemplate"];

/**
 * @member {module:eZmaxAPI/model/EzsigntemplateRequestCompoundV2} objEzsigntemplate
 */
EzsigntemplateEditObjectV2Request.prototype['objEzsigntemplate'] = undefined;






export default EzsigntemplateEditObjectV2Request;

