/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EzsigntemplateCreateObjectV2ResponseMPayload model module.
 * @module eZmaxAPI/model/EzsigntemplateCreateObjectV2ResponseMPayload
 * @version 1.2.0
 */
class EzsigntemplateCreateObjectV2ResponseMPayload {
    /**
     * Constructs a new <code>EzsigntemplateCreateObjectV2ResponseMPayload</code>.
     * Payload for POST /2/object/ezsigntemplate
     * @alias module:eZmaxAPI/model/EzsigntemplateCreateObjectV2ResponseMPayload
     * @param a_pkiEzsigntemplateID {Array.<Number>} An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     */
    constructor(a_pkiEzsigntemplateID) { 
        
        EzsigntemplateCreateObjectV2ResponseMPayload.initialize(this, a_pkiEzsigntemplateID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, a_pkiEzsigntemplateID) { 
        obj['a_pkiEzsigntemplateID'] = a_pkiEzsigntemplateID;
    }

    /**
     * Constructs a <code>EzsigntemplateCreateObjectV2ResponseMPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/EzsigntemplateCreateObjectV2ResponseMPayload} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/EzsigntemplateCreateObjectV2ResponseMPayload} The populated <code>EzsigntemplateCreateObjectV2ResponseMPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EzsigntemplateCreateObjectV2ResponseMPayload();

            if (data.hasOwnProperty('a_pkiEzsigntemplateID')) {
                obj['a_pkiEzsigntemplateID'] = ApiClient.convertToType(data['a_pkiEzsigntemplateID'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EzsigntemplateCreateObjectV2ResponseMPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EzsigntemplateCreateObjectV2ResponseMPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EzsigntemplateCreateObjectV2ResponseMPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['a_pkiEzsigntemplateID'])) {
            throw new Error("Expected the field `a_pkiEzsigntemplateID` to be an array in the JSON data but got " + data['a_pkiEzsigntemplateID']);
        }

        return true;
    }

/**
     * Returns An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @return {Array.<Number>}
     */
    getAPkiEzsigntemplateID() {
        return this.a_pkiEzsigntemplateID;
    }

    /**
     * Sets An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @param {Array.<Number>} a_pkiEzsigntemplateID An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     */
    setAPkiEzsigntemplateID(a_pkiEzsigntemplateID) {
        this['a_pkiEzsigntemplateID'] = a_pkiEzsigntemplateID;
    }

}

EzsigntemplateCreateObjectV2ResponseMPayload.RequiredProperties = ["a_pkiEzsigntemplateID"];

/**
 * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
 * @member {Array.<Number>} a_pkiEzsigntemplateID
 */
EzsigntemplateCreateObjectV2ResponseMPayload.prototype['a_pkiEzsigntemplateID'] = undefined;






export default EzsigntemplateCreateObjectV2ResponseMPayload;

