/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FieldEErrorCode.
* @enum {}
* @readonly
*/
export default class FieldEErrorCode {
    
        /**
         * value: "BADREQUEST"
         * @const
         */
        "BADREQUEST" = "BADREQUEST";

    
        /**
         * value: "BADREQUEST_CLOCKSKEW"
         * @const
         */
        "BADREQUEST_CLOCKSKEW" = "BADREQUEST_CLOCKSKEW";

    
        /**
         * value: "UNAUTHORIZED_BADAUTH"
         * @const
         */
        "UNAUTHORIZED_BADAUTH" = "UNAUTHORIZED_BADAUTH";

    
        /**
         * value: "UNAUTHORIZED_BADMFA"
         * @const
         */
        "UNAUTHORIZED_BADMFA" = "UNAUTHORIZED_BADMFA";

    
        /**
         * value: "UNAUTHORIZED_EXPIRED"
         * @const
         */
        "UNAUTHORIZED_EXPIRED" = "UNAUTHORIZED_EXPIRED";

    
        /**
         * value: "UNAUTHORIZED_REQUEST"
         * @const
         */
        "UNAUTHORIZED_REQUEST" = "UNAUTHORIZED_REQUEST";

    
        /**
         * value: "FORBIDDEN"
         * @const
         */
        "FORBIDDEN" = "FORBIDDEN";

    
        /**
         * value: "FORBIDDEN_CONFIGURATION"
         * @const
         */
        "FORBIDDEN_CONFIGURATION" = "FORBIDDEN_CONFIGURATION";

    
        /**
         * value: "FORBIDDEN_MODULE"
         * @const
         */
        "FORBIDDEN_MODULE" = "FORBIDDEN_MODULE";

    
        /**
         * value: "FORBIDDEN_NOACCESS"
         * @const
         */
        "FORBIDDEN_NOACCESS" = "FORBIDDEN_NOACCESS";

    
        /**
         * value: "FORBIDDEN_PERMISSION"
         * @const
         */
        "FORBIDDEN_PERMISSION" = "FORBIDDEN_PERMISSION";

    
        /**
         * value: "FORBIDDEN_SUBSCRIPTION"
         * @const
         */
        "FORBIDDEN_SUBSCRIPTION" = "FORBIDDEN_SUBSCRIPTION";

    
        /**
         * value: "FORBIDDEN_USERTYPE"
         * @const
         */
        "FORBIDDEN_USERTYPE" = "FORBIDDEN_USERTYPE";

    
        /**
         * value: "FORBIDDEN_USER_ORIGIN_EXTERNAL"
         * @const
         */
        "FORBIDDEN_USER_ORIGIN_EXTERNAL" = "FORBIDDEN_USER_ORIGIN_EXTERNAL";

    
        /**
         * value: "NOTFOUND"
         * @const
         */
        "NOTFOUND" = "NOTFOUND";

    
        /**
         * value: "NOTFOUND_OBJECT"
         * @const
         */
        "NOTFOUND_OBJECT" = "NOTFOUND_OBJECT";

    
        /**
         * value: "NOTFOUND_ROUTE"
         * @const
         */
        "NOTFOUND_ROUTE" = "NOTFOUND_ROUTE";

    
        /**
         * value: "METHODNOTALLOWED"
         * @const
         */
        "METHODNOTALLOWED" = "METHODNOTALLOWED";

    
        /**
         * value: "NOTACCEPTABLE_CONTENT"
         * @const
         */
        "NOTACCEPTABLE_CONTENT" = "NOTACCEPTABLE_CONTENT";

    
        /**
         * value: "NOTACCEPTABLE_LANGUAGE"
         * @const
         */
        "NOTACCEPTABLE_LANGUAGE" = "NOTACCEPTABLE_LANGUAGE";

    
        /**
         * value: "UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING"
         * @const
         */
        "UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING" = "UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING";

    
        /**
         * value: "UNPROCESSABLEENTITY_CANNOTDELETE"
         * @const
         */
        "UNPROCESSABLEENTITY_CANNOTDELETE" = "UNPROCESSABLEENTITY_CANNOTDELETE";

    
        /**
         * value: "UNPROCESSABLEENTITY_CANNOTMODIFY"
         * @const
         */
        "UNPROCESSABLEENTITY_CANNOTMODIFY" = "UNPROCESSABLEENTITY_CANNOTMODIFY";

    
        /**
         * value: "UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT"
         * @const
         */
        "UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT" = "UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT";

    
        /**
         * value: "UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME"
         * @const
         */
        "UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME" = "UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME";

    
        /**
         * value: "UNPROCESSABLEENTITY_DATA_MISSING"
         * @const
         */
        "UNPROCESSABLEENTITY_DATA_MISSING" = "UNPROCESSABLEENTITY_DATA_MISSING";

    
        /**
         * value: "UNPROCESSABLEENTITY_DATA_UNIQUE"
         * @const
         */
        "UNPROCESSABLEENTITY_DATA_UNIQUE" = "UNPROCESSABLEENTITY_DATA_UNIQUE";

    
        /**
         * value: "UNPROCESSABLEENTITY_DATA_VALIDATION"
         * @const
         */
        "UNPROCESSABLEENTITY_DATA_VALIDATION" = "UNPROCESSABLEENTITY_DATA_VALIDATION";

    
        /**
         * value: "UNPROCESSABLEENTITY_DATA_OUTOFBOUND"
         * @const
         */
        "UNPROCESSABLEENTITY_DATA_OUTOFBOUND" = "UNPROCESSABLEENTITY_DATA_OUTOFBOUND";

    
        /**
         * value: "UNPROCESSABLEENTITY_DOWNLOAD_ERROR"
         * @const
         */
        "UNPROCESSABLEENTITY_DOWNLOAD_ERROR" = "UNPROCESSABLEENTITY_DOWNLOAD_ERROR";

    
        /**
         * value: "UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION"
         * @const
         */
        "UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION" = "UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION";

    
        /**
         * value: "UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED"
         * @const
         */
        "UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED" = "UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED";

    
        /**
         * value: "UNPROCESSABLEENTITY_NOTHINGTODO"
         * @const
         */
        "UNPROCESSABLEENTITY_NOTHINGTODO" = "UNPROCESSABLEENTITY_NOTHINGTODO";

    
        /**
         * value: "UNPROCESSABLEENTITY_NOTREADY"
         * @const
         */
        "UNPROCESSABLEENTITY_NOTREADY" = "UNPROCESSABLEENTITY_NOTREADY";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_FORM"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_FORM" = "UNPROCESSABLEENTITY_PDF_FORM";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_SIGNATURE"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_SIGNATURE" = "UNPROCESSABLEENTITY_PDF_SIGNATURE";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE" = "UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_INCOMPATIBLE"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_INCOMPATIBLE" = "UNPROCESSABLEENTITY_PDF_INCOMPATIBLE";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_PASSWORD"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_PASSWORD" = "UNPROCESSABLEENTITY_PDF_PASSWORD";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD" = "UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_REPAIRABLE"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_REPAIRABLE" = "UNPROCESSABLEENTITY_PDF_REPAIRABLE";

    
        /**
         * value: "UNPROCESSABLEENTITY_PDF_XFA"
         * @const
         */
        "UNPROCESSABLEENTITY_PDF_XFA" = "UNPROCESSABLEENTITY_PDF_XFA";

    
        /**
         * value: "UNPROCESSABLEENTITY_TEMPLATE_MISMATCH"
         * @const
         */
        "UNPROCESSABLEENTITY_TEMPLATE_MISMATCH" = "UNPROCESSABLEENTITY_TEMPLATE_MISMATCH";

    
        /**
         * value: "UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD"
         * @const
         */
        "UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD" = "UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD";

    
        /**
         * value: "UNPROCESSABLEENTITY_USER_STAGED"
         * @const
         */
        "UNPROCESSABLEENTITY_USER_STAGED" = "UNPROCESSABLEENTITY_USER_STAGED";

    
        /**
         * value: "TOOMANYREQUESTS"
         * @const
         */
        "TOOMANYREQUESTS" = "TOOMANYREQUESTS";

    
        /**
         * value: "TOOMANYREQUESTS_THIRDPARTY"
         * @const
         */
        "TOOMANYREQUESTS_THIRDPARTY" = "TOOMANYREQUESTS_THIRDPARTY";

    
        /**
         * value: "ERROR_INTERNAL"
         * @const
         */
        "ERROR_INTERNAL" = "ERROR_INTERNAL";

    
        /**
         * value: "ERROR_CONFIGURATION"
         * @const
         */
        "ERROR_CONFIGURATION" = "ERROR_CONFIGURATION";

    
        /**
         * value: "ERROR_NOTIMPLEMENTED"
         * @const
         */
        "ERROR_NOTIMPLEMENTED" = "ERROR_NOTIMPLEMENTED";

    

    /**
    * Returns a <code>FieldEErrorCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:eZmaxAPI/model/FieldEErrorCode} The enum <code>FieldEErrorCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

