/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldEPaymenttermType from './FieldEPaymenttermType';

/**
 * The PaymenttermListElement model module.
 * @module eZmaxAPI/model/PaymenttermListElement
 * @version 1.2.0
 */
class PaymenttermListElement {
    /**
     * Constructs a new <code>PaymenttermListElement</code>.
     * A Paymentterm List Element
     * @alias module:eZmaxAPI/model/PaymenttermListElement
     * @param pkiPaymenttermID {Number} The unique ID of the Paymentterm
     * @param sPaymenttermCode {String} The code of the Paymentterm
     * @param ePaymenttermType {module:eZmaxAPI/model/FieldEPaymenttermType} 
     * @param iPaymenttermDay {Number} The day of the Paymentterm
     * @param sPaymenttermDescriptionX {String} The description of the Paymentterm in the language of the requester
     * @param bPaymenttermIsactive {Boolean} Whether the Paymentterm is active or not
     */
    constructor(pkiPaymenttermID, sPaymenttermCode, ePaymenttermType, iPaymenttermDay, sPaymenttermDescriptionX, bPaymenttermIsactive) { 
        
        PaymenttermListElement.initialize(this, pkiPaymenttermID, sPaymenttermCode, ePaymenttermType, iPaymenttermDay, sPaymenttermDescriptionX, bPaymenttermIsactive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pkiPaymenttermID, sPaymenttermCode, ePaymenttermType, iPaymenttermDay, sPaymenttermDescriptionX, bPaymenttermIsactive) { 
        obj['pkiPaymenttermID'] = pkiPaymenttermID;
        obj['sPaymenttermCode'] = sPaymenttermCode;
        obj['ePaymenttermType'] = ePaymenttermType;
        obj['iPaymenttermDay'] = iPaymenttermDay;
        obj['sPaymenttermDescriptionX'] = sPaymenttermDescriptionX;
        obj['bPaymenttermIsactive'] = bPaymenttermIsactive;
    }

    /**
     * Constructs a <code>PaymenttermListElement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/PaymenttermListElement} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/PaymenttermListElement} The populated <code>PaymenttermListElement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymenttermListElement();

            if (data.hasOwnProperty('pkiPaymenttermID')) {
                obj['pkiPaymenttermID'] = ApiClient.convertToType(data['pkiPaymenttermID'], 'Number');
            }
            if (data.hasOwnProperty('sPaymenttermCode')) {
                obj['sPaymenttermCode'] = ApiClient.convertToType(data['sPaymenttermCode'], 'String');
            }
            if (data.hasOwnProperty('ePaymenttermType')) {
                obj['ePaymenttermType'] = FieldEPaymenttermType.constructFromObject(data['ePaymenttermType']);
            }
            if (data.hasOwnProperty('iPaymenttermDay')) {
                obj['iPaymenttermDay'] = ApiClient.convertToType(data['iPaymenttermDay'], 'Number');
            }
            if (data.hasOwnProperty('sPaymenttermDescriptionX')) {
                obj['sPaymenttermDescriptionX'] = ApiClient.convertToType(data['sPaymenttermDescriptionX'], 'String');
            }
            if (data.hasOwnProperty('bPaymenttermIsactive')) {
                obj['bPaymenttermIsactive'] = ApiClient.convertToType(data['bPaymenttermIsactive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymenttermListElement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymenttermListElement</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymenttermListElement.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['sPaymenttermCode'] && !(typeof data['sPaymenttermCode'] === 'string' || data['sPaymenttermCode'] instanceof String)) {
            throw new Error("Expected the field `sPaymenttermCode` to be a primitive type in the JSON string but got " + data['sPaymenttermCode']);
        }
        // ensure the json data is a string
        if (data['sPaymenttermDescriptionX'] && !(typeof data['sPaymenttermDescriptionX'] === 'string' || data['sPaymenttermDescriptionX'] instanceof String)) {
            throw new Error("Expected the field `sPaymenttermDescriptionX` to be a primitive type in the JSON string but got " + data['sPaymenttermDescriptionX']);
        }

        return true;
    }

/**
     * Returns The unique ID of the Paymentterm
     * @return {Number}
     */
    getPkiPaymenttermID() {
        return this.pkiPaymenttermID;
    }

    /**
     * Sets The unique ID of the Paymentterm
     * @param {Number} pkiPaymenttermID The unique ID of the Paymentterm
     */
    setPkiPaymenttermID(pkiPaymenttermID) {
        this['pkiPaymenttermID'] = pkiPaymenttermID;
    }
/**
     * Returns The code of the Paymentterm
     * @return {String}
     */
    getSPaymenttermCode() {
        return this.sPaymenttermCode;
    }

    /**
     * Sets The code of the Paymentterm
     * @param {String} sPaymenttermCode The code of the Paymentterm
     */
    setSPaymenttermCode(sPaymenttermCode) {
        this['sPaymenttermCode'] = sPaymenttermCode;
    }
/**
     * @return {module:eZmaxAPI/model/FieldEPaymenttermType}
     */
    getEPaymenttermType() {
        return this.ePaymenttermType;
    }

    /**
     * @param {module:eZmaxAPI/model/FieldEPaymenttermType} ePaymenttermType
     */
    setEPaymenttermType(ePaymenttermType) {
        this['ePaymenttermType'] = ePaymenttermType;
    }
/**
     * Returns The day of the Paymentterm
     * minimum: 0
     * maximum: 255
     * @return {Number}
     */
    getIPaymenttermDay() {
        return this.iPaymenttermDay;
    }

    /**
     * Sets The day of the Paymentterm
     * @param {Number} iPaymenttermDay The day of the Paymentterm
     */
    setIPaymenttermDay(iPaymenttermDay) {
        this['iPaymenttermDay'] = iPaymenttermDay;
    }
/**
     * Returns The description of the Paymentterm in the language of the requester
     * @return {String}
     */
    getSPaymenttermDescriptionX() {
        return this.sPaymenttermDescriptionX;
    }

    /**
     * Sets The description of the Paymentterm in the language of the requester
     * @param {String} sPaymenttermDescriptionX The description of the Paymentterm in the language of the requester
     */
    setSPaymenttermDescriptionX(sPaymenttermDescriptionX) {
        this['sPaymenttermDescriptionX'] = sPaymenttermDescriptionX;
    }
/**
     * Returns Whether the Paymentterm is active or not
     * @return {Boolean}
     */
    getBPaymenttermIsactive() {
        return this.bPaymenttermIsactive;
    }

    /**
     * Sets Whether the Paymentterm is active or not
     * @param {Boolean} bPaymenttermIsactive Whether the Paymentterm is active or not
     */
    setBPaymenttermIsactive(bPaymenttermIsactive) {
        this['bPaymenttermIsactive'] = bPaymenttermIsactive;
    }

}

PaymenttermListElement.RequiredProperties = ["pkiPaymenttermID", "sPaymenttermCode", "ePaymenttermType", "iPaymenttermDay", "sPaymenttermDescriptionX", "bPaymenttermIsactive"];

/**
 * The unique ID of the Paymentterm
 * @member {Number} pkiPaymenttermID
 */
PaymenttermListElement.prototype['pkiPaymenttermID'] = undefined;

/**
 * The code of the Paymentterm
 * @member {String} sPaymenttermCode
 */
PaymenttermListElement.prototype['sPaymenttermCode'] = undefined;

/**
 * @member {module:eZmaxAPI/model/FieldEPaymenttermType} ePaymenttermType
 */
PaymenttermListElement.prototype['ePaymenttermType'] = undefined;

/**
 * The day of the Paymentterm
 * @member {Number} iPaymenttermDay
 */
PaymenttermListElement.prototype['iPaymenttermDay'] = undefined;

/**
 * The description of the Paymentterm in the language of the requester
 * @member {String} sPaymenttermDescriptionX
 */
PaymenttermListElement.prototype['sPaymenttermDescriptionX'] = undefined;

/**
 * Whether the Paymentterm is active or not
 * @member {Boolean} bPaymenttermIsactive
 */
PaymenttermListElement.prototype['bPaymenttermIsactive'] = undefined;






export default PaymenttermListElement;

