/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProvinceAutocompleteElementResponse from './ProvinceAutocompleteElementResponse';

/**
 * The ProvinceGetAutocompleteV2ResponseMPayload model module.
 * @module eZmaxAPI/model/ProvinceGetAutocompleteV2ResponseMPayload
 * @version 1.2.0
 */
class ProvinceGetAutocompleteV2ResponseMPayload {
    /**
     * Constructs a new <code>ProvinceGetAutocompleteV2ResponseMPayload</code>.
     * Payload for POST /2/object/province/getAutocomplete
     * @alias module:eZmaxAPI/model/ProvinceGetAutocompleteV2ResponseMPayload
     * @param a_objProvince {Array.<module:eZmaxAPI/model/ProvinceAutocompleteElementResponse>} An array of Province autocomplete element response.
     */
    constructor(a_objProvince) { 
        
        ProvinceGetAutocompleteV2ResponseMPayload.initialize(this, a_objProvince);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, a_objProvince) { 
        obj['a_objProvince'] = a_objProvince;
    }

    /**
     * Constructs a <code>ProvinceGetAutocompleteV2ResponseMPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/ProvinceGetAutocompleteV2ResponseMPayload} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/ProvinceGetAutocompleteV2ResponseMPayload} The populated <code>ProvinceGetAutocompleteV2ResponseMPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProvinceGetAutocompleteV2ResponseMPayload();

            if (data.hasOwnProperty('a_objProvince')) {
                obj['a_objProvince'] = ApiClient.convertToType(data['a_objProvince'], [ProvinceAutocompleteElementResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProvinceGetAutocompleteV2ResponseMPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProvinceGetAutocompleteV2ResponseMPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProvinceGetAutocompleteV2ResponseMPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['a_objProvince']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['a_objProvince'])) {
                throw new Error("Expected the field `a_objProvince` to be an array in the JSON data but got " + data['a_objProvince']);
            }
            // validate the optional field `a_objProvince` (array)
            for (const item of data['a_objProvince']) {
                ProvinceAutocompleteElementResponse.validateJSON(item);
            };
        }

        return true;
    }

/**
     * Returns An array of Province autocomplete element response.
     * @return {Array.<module:eZmaxAPI/model/ProvinceAutocompleteElementResponse>}
     */
    getAObjProvince() {
        return this.a_objProvince;
    }

    /**
     * Sets An array of Province autocomplete element response.
     * @param {Array.<module:eZmaxAPI/model/ProvinceAutocompleteElementResponse>} a_objProvince An array of Province autocomplete element response.
     */
    setAObjProvince(a_objProvince) {
        this['a_objProvince'] = a_objProvince;
    }

}

ProvinceGetAutocompleteV2ResponseMPayload.RequiredProperties = ["a_objProvince"];

/**
 * An array of Province autocomplete element response.
 * @member {Array.<module:eZmaxAPI/model/ProvinceAutocompleteElementResponse>} a_objProvince
 */
ProvinceGetAutocompleteV2ResponseMPayload.prototype['a_objProvince'] = undefined;






export default ProvinceGetAutocompleteV2ResponseMPayload;

