/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserstagedListElement from './UserstagedListElement';

/**
 * The UserstagedGetListV1ResponseMPayloadAllOf model module.
 * @module eZmaxAPI/model/UserstagedGetListV1ResponseMPayloadAllOf
 * @version 1.1.17
 */
class UserstagedGetListV1ResponseMPayloadAllOf {
    /**
     * Constructs a new <code>UserstagedGetListV1ResponseMPayloadAllOf</code>.
     * @alias module:eZmaxAPI/model/UserstagedGetListV1ResponseMPayloadAllOf
     * @param a_objUserstaged {Array.<module:eZmaxAPI/model/UserstagedListElement>} 
     */
    constructor(a_objUserstaged) { 
        
        UserstagedGetListV1ResponseMPayloadAllOf.initialize(this, a_objUserstaged);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, a_objUserstaged) { 
        obj['a_objUserstaged'] = a_objUserstaged;
    }

    /**
     * Constructs a <code>UserstagedGetListV1ResponseMPayloadAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:eZmaxAPI/model/UserstagedGetListV1ResponseMPayloadAllOf} obj Optional instance to populate.
     * @return {module:eZmaxAPI/model/UserstagedGetListV1ResponseMPayloadAllOf} The populated <code>UserstagedGetListV1ResponseMPayloadAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserstagedGetListV1ResponseMPayloadAllOf();

            if (data.hasOwnProperty('a_objUserstaged')) {
                obj['a_objUserstaged'] = ApiClient.convertToType(data['a_objUserstaged'], [UserstagedListElement]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserstagedGetListV1ResponseMPayloadAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserstagedGetListV1ResponseMPayloadAllOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserstagedGetListV1ResponseMPayloadAllOf.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['a_objUserstaged']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['a_objUserstaged'])) {
                throw new Error("Expected the field `a_objUserstaged` to be an array in the JSON data but got " + data['a_objUserstaged']);
            }
            // validate the optional field `a_objUserstaged` (array)
            for (const item of data['a_objUserstaged']) {
                UserstagedListElement.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:eZmaxAPI/model/UserstagedListElement>}
     */
    getAObjUserstaged() {
        return this.a_objUserstaged;
    }

    /**
     * @param {Array.<module:eZmaxAPI/model/UserstagedListElement>} a_objUserstaged
     */
    setAObjUserstaged(a_objUserstaged) {
        this['a_objUserstaged'] = a_objUserstaged;
    }

}

UserstagedGetListV1ResponseMPayloadAllOf.RequiredProperties = ["a_objUserstaged"];

/**
 * @member {Array.<module:eZmaxAPI/model/UserstagedListElement>} a_objUserstaged
 */
UserstagedGetListV1ResponseMPayloadAllOf.prototype['a_objUserstaged'] = undefined;






export default UserstagedGetListV1ResponseMPayloadAllOf;

